// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindFit_Intelligence_Backend.Models;

#nullable disable

namespace MindFit_Intelligence_Backend.Migrations
{
    [DbContext(typeof(MindFitIntelligenceContext))]
    [Migration("20260218131758_rolNull")]
    partial class rolNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdGrupo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Grupo", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.GrupoPermiso", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdGrupo", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("GrupoPermiso", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPermiso");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaResponsable", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("PersonaResponsable", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaSocio", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoSocio")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaFinActividades")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaInicioActividades")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("date");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ObraSocial")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Plan")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pregunta")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Respuesta")
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("RespuestaNotificacion")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("PersonaSocio", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.UsuarioGrupo", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdGrupo");

                    b.HasIndex("IdGrupo");

                    b.ToTable("UsuarioGrupo", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.GrupoPermiso", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Grupo", "Grupo")
                        .WithMany("GrupoPermisos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.Permiso", "Permiso")
                        .WithMany("GrupoPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaResponsable", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Usuario", "Usuario")
                        .WithOne("PersonaResponsable")
                        .HasForeignKey("MindFit_Intelligence_Backend.Models.PersonaResponsable", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaSocio", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Usuario", "Usuario")
                        .WithOne("PersonaSocio")
                        .HasForeignKey("MindFit_Intelligence_Backend.Models.PersonaSocio", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.UsuarioGrupo", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Grupo", "Grupo")
                        .WithMany("UsuarioGrupos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.Usuario", "Usuario")
                        .WithMany("UsuarioGrupos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Grupo", b =>
                {
                    b.Navigation("GrupoPermisos");

                    b.Navigation("UsuarioGrupos");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Permiso", b =>
                {
                    b.Navigation("GrupoPermisos");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Usuario", b =>
                {
                    b.Navigation("PersonaResponsable");

                    b.Navigation("PersonaSocio");

                    b.Navigation("UsuarioGrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
