// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Comentario: Nota informativa automática que indica que el archivo fue generado
// por Prisma y qué paquetes se asumen instalados para usarlo (prisma y dotenv).

// Importa y ejecuta automáticamente la configuración de dotenv.
// Esto carga variables de entorno desde un archivo `.env` en `process.env`.
import "dotenv/config";

// Importa la función `defineConfig` desde el paquete de configuración de Prisma.
// `defineConfig` proporciona tipado y validación para la configuración en TypeScript.
import { defineConfig } from "prisma/config";

// Exporta por defecto la configuración de Prisma usando `defineConfig`.
// Esto facilita autocompletado y ayuda al compilador de TypeScript.
export default defineConfig({
  // Ruta al archivo de esquema de Prisma (`schema.prisma`) que define modelos
  // y generadores como el cliente de Prisma.
  schema: "prisma/schema.prisma",

  // Configuración relacionada a migraciones. `path` indica dónde se guardan
  // los archivos de migración generados por Prisma.
  migrations: {
    path: "prisma/migrations",
  },

  // Define la fuente de datos (la base de datos). La `url` se toma de la
  // variable de entorno `DATABASE_URL`. El operador `!` le dice a TypeScript
  // que asumimos que esta variable estará definida en tiempo de ejecución.
  datasource: {
    url: process.env["DATABASE_URL"]!,
  },

});
