// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindFit_Intelligence_Backend.Models.Master;

#nullable disable

namespace MindFit_Intelligence_Backend.Migrations.Master
{
    [DbContext(typeof(MindFitMasterContext))]
    partial class MindFitMasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Master.Gym", b =>
                {
                    b.Property<int>("IdGym")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGym"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NombreGym")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdGym");

                    b.ToTable("Gym", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Master.PersonaResponsableMaster", b =>
                {
                    b.Property<int>("IdUsuarioMaster")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuarioMaster");

                    b.ToTable("PersonaResponsableMaster", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Master.UsuarioMaster", b =>
                {
                    b.Property<int>("IdUsuarioMaster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioMaster"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<int>("IdGym")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuarioMaster");

                    b.HasIndex("IdGym");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UsuarioMaster", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Master.PersonaResponsableMaster", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Master.UsuarioMaster", "UsuarioMaster")
                        .WithOne("PersonaResponsableMaster")
                        .HasForeignKey("MindFit_Intelligence_Backend.Models.Master.PersonaResponsableMaster", "IdUsuarioMaster")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioMaster");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Master.UsuarioMaster", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Master.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("IdGym")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Master.UsuarioMaster", b =>
                {
                    b.Navigation("PersonaResponsableMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
