// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindFit_Intelligence_Backend.Models;

#nullable disable

namespace MindFit_Intelligence_Backend.Migrations
{
    [DbContext(typeof(MindFitIntelligenceContext))]
    partial class MindFitIntelligenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Calentamiento", b =>
                {
                    b.Property<int>("IdCalentamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalentamiento"));

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdRutina")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdCalentamiento");

                    b.HasIndex("IdEjercicio");

                    b.HasIndex("IdRutina");

                    b.ToTable("Calentamiento", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Cuota", b =>
                {
                    b.Property<int>("IdCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuota"));

                    b.Property<string>("EstadoCuota")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaFinPeriodo")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicioPeriodo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCuota");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Cuota", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.CupoFecha", b =>
                {
                    b.Property<int>("IdCupoFecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCupoFecha"));

                    b.Property<int>("CupoActual")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdDiaRangoHorario")
                        .HasColumnType("int");

                    b.HasKey("IdCupoFecha");

                    b.HasIndex("IdDiaRangoHorario", "Fecha")
                        .IsUnique();

                    b.ToTable("CupoFecha", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Dia", b =>
                {
                    b.Property<int>("IdDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDia"));

                    b.Property<string>("NombreDia")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("IdDia");

                    b.HasIndex("NombreDia")
                        .IsUnique();

                    b.ToTable("Dia", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.DiaRangoHorario", b =>
                {
                    b.Property<int>("IdDiaRangoHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiaRangoHorario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("int");

                    b.Property<int>("IdDia")
                        .HasColumnType("int");

                    b.Property<int>("IdRangoHorario")
                        .HasColumnType("int");

                    b.HasKey("IdDiaRangoHorario");

                    b.HasIndex("IdRangoHorario");

                    b.HasIndex("IdDia", "IdRangoHorario")
                        .IsUnique();

                    b.ToTable("DiaRangoHorario", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.DiaRangoHorarioResponsable", b =>
                {
                    b.Property<int>("IdDiaRangoHorarioResponsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiaRangoHorarioResponsable"));

                    b.Property<int>("IdDiaRangoHorario")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioResponsable")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdDiaRangoHorarioResponsable");

                    b.HasIndex("IdUsuarioResponsable");

                    b.HasIndex("IdDiaRangoHorario", "IdUsuarioResponsable")
                        .IsUnique();

                    b.ToTable("DiaRangoHorarioResponsable", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Ejercicio", b =>
                {
                    b.Property<int>("IdEjercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEjercicio"));

                    b.Property<string>("DescEjercicio")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int?>("IdEquipamiento")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupoMuscular")
                        .HasColumnType("int");

                    b.Property<int?>("IdMaquina")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEjercicio")
                        .HasColumnType("int");

                    b.HasKey("IdEjercicio");

                    b.HasIndex("IdEquipamiento");

                    b.HasIndex("IdGrupoMuscular");

                    b.HasIndex("IdMaquina");

                    b.HasIndex("IdTipoEjercicio");

                    b.ToTable("Ejercicio", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Entrenamiento", b =>
                {
                    b.Property<int>("IdEntrenamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntrenamiento"));

                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdRutina")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoAsignado")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoDescansoSegundos")
                        .HasColumnType("int");

                    b.HasKey("IdEntrenamiento");

                    b.HasIndex("IdEjercicio");

                    b.HasIndex("IdRutina");

                    b.ToTable("Entrenamiento", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Equipamiento", b =>
                {
                    b.Property<int>("IdEquipamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipamiento"));

                    b.Property<decimal>("CostoAdquisicion")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal?>("PesoFijoKg")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdEquipamiento");

                    b.ToTable("Equipamiento", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Estiramiento", b =>
                {
                    b.Property<int>("IdEstiramiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstiramiento"));

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdRutina")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdEstiramiento");

                    b.HasIndex("IdEjercicio");

                    b.HasIndex("IdRutina");

                    b.ToTable("Estiramiento", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdGrupo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Grupo", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.GrupoMuscular", b =>
                {
                    b.Property<int>("IdGrupoMuscular")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoMuscular"));

                    b.Property<string>("IdMapaAnatomico")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("NombreMusculo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("IdGrupoMuscular");

                    b.ToTable("GrupoMuscular", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.GrupoPermiso", b =>
                {
                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdGrupo", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("GrupoPermiso", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Maquina", b =>
                {
                    b.Property<int>("IdMaquina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaquina"));

                    b.Property<decimal>("CostoAdquisicion")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<bool>("EsElectrica")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFabricacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreMaquina")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal?>("PesoMaximoLingotera")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdMaquina");

                    b.ToTable("Maquina", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PerfilIA", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("DisponibilidadHoraria")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EjerciciosAEvitar")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EjerciciosPreferidos")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MotivacionPersonal")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NivelExperiencia")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ObjetivoPrincipal")
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdUsuario");

                    b.ToTable("PerfilIA", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdPermiso");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaResponsable", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("PersonaResponsable", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaSocio", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoSocio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaInicioActividades")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("date");

                    b.Property<string>("Genero")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ObraSocial")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pregunta")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Respuesta")
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("RespuestaNotificacion")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.ToTable("PersonaSocio", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RangoHorario", b =>
                {
                    b.Property<int>("IdRangoHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRangoHorario"));

                    b.Property<TimeSpan>("HoraDesde")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraHasta")
                        .HasColumnType("time");

                    b.HasKey("IdRangoHorario");

                    b.HasIndex("HoraDesde", "HoraHasta")
                        .IsUnique();

                    b.ToTable("RangoHorario", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Rutina", b =>
                {
                    b.Property<int>("IdRutina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutina"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDia")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonaSocio")
                        .HasColumnType("int");

                    b.HasKey("IdRutina");

                    b.HasIndex("IdDia");

                    b.HasIndex("IdPersonaSocio", "IdDia")
                        .IsUnique();

                    b.ToTable("Rutina", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorial", b =>
                {
                    b.Property<int>("IdRutinaHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutinaHistorial"));

                    b.Property<bool>("ActivoSnapshot")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaSnapshot")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRutina")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("IdRutinaHistorial");

                    b.HasIndex("IdRutina", "Version")
                        .IsUnique();

                    b.ToTable("RutinaHistorial", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorialCalentamiento", b =>
                {
                    b.Property<int>("IdRutinaHistorialCalentamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutinaHistorialCalentamiento"));

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdRutinaHistorial")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdRutinaHistorialCalentamiento");

                    b.HasIndex("IdRutinaHistorial");

                    b.ToTable("RutinaHistorialCalentamiento", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorialEntrenamiento", b =>
                {
                    b.Property<int>("IdRutinaHistorialEntrenamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutinaHistorialEntrenamiento"));

                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdRutinaHistorial")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoAsignado")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoDescansoSegundos")
                        .HasColumnType("int");

                    b.HasKey("IdRutinaHistorialEntrenamiento");

                    b.HasIndex("IdRutinaHistorial");

                    b.ToTable("RutinaHistorialEntrenamiento", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorialEstiramiento", b =>
                {
                    b.Property<int>("IdRutinaHistorialEstiramiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRutinaHistorialEstiramiento"));

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("IdEjercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdRutinaHistorial")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdRutinaHistorialEstiramiento");

                    b.HasIndex("IdRutinaHistorial");

                    b.ToTable("RutinaHistorialEstiramiento", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.TipoEjercicio", b =>
                {
                    b.Property<int>("IdTipoEjercicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoEjercicio"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("IdTipoEjercicio");

                    b.ToTable("TipoEjercicio", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<string>("EstadoTurno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("date");

                    b.Property<int>("IdCupoFecha")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioResponsable")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioSocio")
                        .HasColumnType("int");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdCupoFecha");

                    b.HasIndex("IdUsuarioResponsable");

                    b.HasIndex("IdUsuarioSocio");

                    b.ToTable("Turno", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.UsuarioGrupo", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdGrupo");

                    b.HasIndex("IdGrupo");

                    b.ToTable("UsuarioGrupo", (string)null);
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Calentamiento", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("IdEjercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.Rutina", "Rutina")
                        .WithMany("Calentamientos")
                        .HasForeignKey("IdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Cuota", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.PersonaSocio", "PersonaSocio")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaSocio");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.CupoFecha", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.DiaRangoHorario", "DiaRangoHorario")
                        .WithMany("CupoFechas")
                        .HasForeignKey("IdDiaRangoHorario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiaRangoHorario");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.DiaRangoHorario", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Dia", "Dia")
                        .WithMany("DiaRangosHorarios")
                        .HasForeignKey("IdDia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.RangoHorario", "RangoHorario")
                        .WithMany("DiaRangosHorarios")
                        .HasForeignKey("IdRangoHorario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dia");

                    b.Navigation("RangoHorario");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.DiaRangoHorarioResponsable", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.DiaRangoHorario", "DiaRangoHorario")
                        .WithMany("DiaRangoHorarioResponsables")
                        .HasForeignKey("IdDiaRangoHorario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.PersonaResponsable", "PersonaResponsable")
                        .WithMany("DiaRangoHorarioResponsables")
                        .HasForeignKey("IdUsuarioResponsable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaRangoHorario");

                    b.Navigation("PersonaResponsable");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Ejercicio", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Equipamiento", "Equipamiento")
                        .WithMany()
                        .HasForeignKey("IdEquipamiento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MindFit_Intelligence_Backend.Models.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Ejercicios")
                        .HasForeignKey("IdGrupoMuscular")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("IdMaquina")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MindFit_Intelligence_Backend.Models.TipoEjercicio", "TipoEjercicio")
                        .WithMany("Ejercicios")
                        .HasForeignKey("IdTipoEjercicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamiento");

                    b.Navigation("GrupoMuscular");

                    b.Navigation("Maquina");

                    b.Navigation("TipoEjercicio");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Entrenamiento", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("IdEjercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.Rutina", "Rutina")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("IdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Estiramiento", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("IdEjercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.Rutina", "Rutina")
                        .WithMany("Estiramientos")
                        .HasForeignKey("IdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.GrupoPermiso", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Grupo", "Grupo")
                        .WithMany("GrupoPermisos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.Permiso", "Permiso")
                        .WithMany("GrupoPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PerfilIA", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.PersonaSocio", "PersonaSocio")
                        .WithOne("PerfilIA")
                        .HasForeignKey("MindFit_Intelligence_Backend.Models.PerfilIA", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaSocio");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaResponsable", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Usuario", "Usuario")
                        .WithOne("PersonaResponsable")
                        .HasForeignKey("MindFit_Intelligence_Backend.Models.PersonaResponsable", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaSocio", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Usuario", "Usuario")
                        .WithOne("PersonaSocio")
                        .HasForeignKey("MindFit_Intelligence_Backend.Models.PersonaSocio", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Rutina", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Dia", "Dia")
                        .WithMany("Rutinas")
                        .HasForeignKey("IdDia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.PersonaSocio", "PersonaSocio")
                        .WithMany("Rutinas")
                        .HasForeignKey("IdPersonaSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dia");

                    b.Navigation("PersonaSocio");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorial", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Rutina", "Rutina")
                        .WithMany("Historiales")
                        .HasForeignKey("IdRutina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorialCalentamiento", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.RutinaHistorial", "RutinaHistorial")
                        .WithMany("Calentamientos")
                        .HasForeignKey("IdRutinaHistorial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaHistorial");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorialEntrenamiento", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.RutinaHistorial", "RutinaHistorial")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("IdRutinaHistorial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaHistorial");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorialEstiramiento", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.RutinaHistorial", "RutinaHistorial")
                        .WithMany("Estiramientos")
                        .HasForeignKey("IdRutinaHistorial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutinaHistorial");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Turno", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.CupoFecha", "CupoFecha")
                        .WithMany("Turnos")
                        .HasForeignKey("IdCupoFecha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.PersonaResponsable", "PersonaResponsable")
                        .WithMany("Turnos")
                        .HasForeignKey("IdUsuarioResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.PersonaSocio", "PersonaSocio")
                        .WithMany("Turnos")
                        .HasForeignKey("IdUsuarioSocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CupoFecha");

                    b.Navigation("PersonaResponsable");

                    b.Navigation("PersonaSocio");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.UsuarioGrupo", b =>
                {
                    b.HasOne("MindFit_Intelligence_Backend.Models.Grupo", "Grupo")
                        .WithMany("UsuarioGrupos")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindFit_Intelligence_Backend.Models.Usuario", "Usuario")
                        .WithMany("UsuarioGrupos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.CupoFecha", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Dia", b =>
                {
                    b.Navigation("DiaRangosHorarios");

                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.DiaRangoHorario", b =>
                {
                    b.Navigation("CupoFechas");

                    b.Navigation("DiaRangoHorarioResponsables");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Grupo", b =>
                {
                    b.Navigation("GrupoPermisos");

                    b.Navigation("UsuarioGrupos");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.GrupoMuscular", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Permiso", b =>
                {
                    b.Navigation("GrupoPermisos");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaResponsable", b =>
                {
                    b.Navigation("DiaRangoHorarioResponsables");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.PersonaSocio", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("PerfilIA");

                    b.Navigation("Rutinas");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RangoHorario", b =>
                {
                    b.Navigation("DiaRangosHorarios");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Rutina", b =>
                {
                    b.Navigation("Calentamientos");

                    b.Navigation("Entrenamientos");

                    b.Navigation("Estiramientos");

                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.RutinaHistorial", b =>
                {
                    b.Navigation("Calentamientos");

                    b.Navigation("Entrenamientos");

                    b.Navigation("Estiramientos");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.TipoEjercicio", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("MindFit_Intelligence_Backend.Models.Usuario", b =>
                {
                    b.Navigation("PersonaResponsable");

                    b.Navigation("PersonaSocio");

                    b.Navigation("UsuarioGrupos");
                });
#pragma warning restore 612, 618
        }
    }
}
